[package]
name = "tortuga"
version = "0.1.0"
authors = ["christian rivasseau <christian@lefty.io>"]

[dependencies]
rusqlite = { version = "0.14.0", features = ["bundled"] }
dotenv = "0.9.0"
getopts = "0.2"
log = "0.4"
simplelog = "^0.5.0"
grpcio = "0.3"
