// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tortuga/tortuga_params.proto

#ifndef PROTOBUF_tortuga_2ftortuga_5fparams_2eproto__INCLUDED
#define PROTOBUF_tortuga_2ftortuga_5fparams_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)

namespace protobuf_tortuga_2ftortuga_5fparams_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsTortugaBridgeOptsImpl();
void InitDefaultsTortugaBridgeOpts();
void InitDefaultsTortugaOutputImpl();
void InitDefaultsTortugaOutput();
inline void InitDefaults() {
  InitDefaultsTortugaBridgeOpts();
  InitDefaultsTortugaOutput();
}
}  // namespace protobuf_tortuga_2ftortuga_5fparams_2eproto
namespace tortuga {
class TortugaBridgeOpts;
class TortugaBridgeOptsDefaultTypeInternal;
extern TortugaBridgeOptsDefaultTypeInternal _TortugaBridgeOpts_default_instance_;
class TortugaOutput;
class TortugaOutputDefaultTypeInternal;
extern TortugaOutputDefaultTypeInternal _TortugaOutput_default_instance_;
}  // namespace tortuga
namespace tortuga {

// ===================================================================

class TortugaBridgeOpts : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tortuga.TortugaBridgeOpts) */ {
 public:
  TortugaBridgeOpts();
  virtual ~TortugaBridgeOpts();

  TortugaBridgeOpts(const TortugaBridgeOpts& from);

  inline TortugaBridgeOpts& operator=(const TortugaBridgeOpts& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TortugaBridgeOpts(TortugaBridgeOpts&& from) noexcept
    : TortugaBridgeOpts() {
    *this = ::std::move(from);
  }

  inline TortugaBridgeOpts& operator=(TortugaBridgeOpts&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TortugaBridgeOpts& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TortugaBridgeOpts* internal_default_instance() {
    return reinterpret_cast<const TortugaBridgeOpts*>(
               &_TortugaBridgeOpts_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(TortugaBridgeOpts* other);
  friend void swap(TortugaBridgeOpts& a, TortugaBridgeOpts& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TortugaBridgeOpts* New() const PROTOBUF_FINAL { return New(NULL); }

  TortugaBridgeOpts* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TortugaBridgeOpts& from);
  void MergeFrom(const TortugaBridgeOpts& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TortugaBridgeOpts* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 timeout_seconds = 1;
  bool has_timeout_seconds() const;
  void clear_timeout_seconds();
  static const int kTimeoutSecondsFieldNumber = 1;
  ::google::protobuf::int32 timeout_seconds() const;
  void set_timeout_seconds(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tortuga.TortugaBridgeOpts)
 private:
  void set_has_timeout_seconds();
  void clear_has_timeout_seconds();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 timeout_seconds_;
  friend struct ::protobuf_tortuga_2ftortuga_5fparams_2eproto::TableStruct;
  friend void ::protobuf_tortuga_2ftortuga_5fparams_2eproto::InitDefaultsTortugaBridgeOptsImpl();
};
// -------------------------------------------------------------------

class TortugaOutput : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tortuga.TortugaOutput) */ {
 public:
  TortugaOutput();
  virtual ~TortugaOutput();

  TortugaOutput(const TortugaOutput& from);

  inline TortugaOutput& operator=(const TortugaOutput& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TortugaOutput(TortugaOutput&& from) noexcept
    : TortugaOutput() {
    *this = ::std::move(from);
  }

  inline TortugaOutput& operator=(TortugaOutput&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TortugaOutput& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TortugaOutput* internal_default_instance() {
    return reinterpret_cast<const TortugaOutput*>(
               &_TortugaOutput_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(TortugaOutput* other);
  friend void swap(TortugaOutput& a, TortugaOutput& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TortugaOutput* New() const PROTOBUF_FINAL { return New(NULL); }

  TortugaOutput* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TortugaOutput& from);
  void MergeFrom(const TortugaOutput& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TortugaOutput* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string output = 1;
  bool has_output() const;
  void clear_output();
  static const int kOutputFieldNumber = 1;
  const ::std::string& output() const;
  void set_output(const ::std::string& value);
  #if LANG_CXX11
  void set_output(::std::string&& value);
  #endif
  void set_output(const char* value);
  void set_output(const char* value, size_t size);
  ::std::string* mutable_output();
  ::std::string* release_output();
  void set_allocated_output(::std::string* output);

  // @@protoc_insertion_point(class_scope:tortuga.TortugaOutput)
 private:
  void set_has_output();
  void clear_has_output();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr output_;
  friend struct ::protobuf_tortuga_2ftortuga_5fparams_2eproto::TableStruct;
  friend void ::protobuf_tortuga_2ftortuga_5fparams_2eproto::InitDefaultsTortugaOutputImpl();
};
// ===================================================================

static const int kBridgeFieldNumber = 50007;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::tortuga::TortugaBridgeOpts >, 11, false >
  bridge;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TortugaBridgeOpts

// optional int32 timeout_seconds = 1;
inline bool TortugaBridgeOpts::has_timeout_seconds() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TortugaBridgeOpts::set_has_timeout_seconds() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TortugaBridgeOpts::clear_has_timeout_seconds() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TortugaBridgeOpts::clear_timeout_seconds() {
  timeout_seconds_ = 0;
  clear_has_timeout_seconds();
}
inline ::google::protobuf::int32 TortugaBridgeOpts::timeout_seconds() const {
  // @@protoc_insertion_point(field_get:tortuga.TortugaBridgeOpts.timeout_seconds)
  return timeout_seconds_;
}
inline void TortugaBridgeOpts::set_timeout_seconds(::google::protobuf::int32 value) {
  set_has_timeout_seconds();
  timeout_seconds_ = value;
  // @@protoc_insertion_point(field_set:tortuga.TortugaBridgeOpts.timeout_seconds)
}

// -------------------------------------------------------------------

// TortugaOutput

// optional string output = 1;
inline bool TortugaOutput::has_output() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TortugaOutput::set_has_output() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TortugaOutput::clear_has_output() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TortugaOutput::clear_output() {
  output_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_output();
}
inline const ::std::string& TortugaOutput::output() const {
  // @@protoc_insertion_point(field_get:tortuga.TortugaOutput.output)
  return output_.GetNoArena();
}
inline void TortugaOutput::set_output(const ::std::string& value) {
  set_has_output();
  output_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tortuga.TortugaOutput.output)
}
#if LANG_CXX11
inline void TortugaOutput::set_output(::std::string&& value) {
  set_has_output();
  output_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tortuga.TortugaOutput.output)
}
#endif
inline void TortugaOutput::set_output(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_output();
  output_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tortuga.TortugaOutput.output)
}
inline void TortugaOutput::set_output(const char* value, size_t size) {
  set_has_output();
  output_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tortuga.TortugaOutput.output)
}
inline ::std::string* TortugaOutput::mutable_output() {
  set_has_output();
  // @@protoc_insertion_point(field_mutable:tortuga.TortugaOutput.output)
  return output_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TortugaOutput::release_output() {
  // @@protoc_insertion_point(field_release:tortuga.TortugaOutput.output)
  clear_has_output();
  return output_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TortugaOutput::set_allocated_output(::std::string* output) {
  if (output != NULL) {
    set_has_output();
  } else {
    clear_has_output();
  }
  output_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), output);
  // @@protoc_insertion_point(field_set_allocated:tortuga.TortugaOutput.output)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace tortuga

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tortuga_2ftortuga_5fparams_2eproto__INCLUDED
