// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tortuga/tortuga_params.proto

#include "tortuga/tortuga_params.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace tortuga {
class TortugaBridgeOptsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TortugaBridgeOpts>
      _instance;
} _TortugaBridgeOpts_default_instance_;
}  // namespace tortuga
namespace protobuf_tortuga_2ftortuga_5fparams_2eproto {
void InitDefaultsTortugaBridgeOptsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::tortuga::_TortugaBridgeOpts_default_instance_;
    new (ptr) ::tortuga::TortugaBridgeOpts();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tortuga::TortugaBridgeOpts::InitAsDefaultInstance();
}

void InitDefaultsTortugaBridgeOpts() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsTortugaBridgeOptsImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tortuga::TortugaBridgeOpts, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tortuga::TortugaBridgeOpts, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tortuga::TortugaBridgeOpts, timeout_seconds_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::tortuga::TortugaBridgeOpts)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::tortuga::_TortugaBridgeOpts_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "tortuga/tortuga_params.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\034tortuga/tortuga_params.proto\022\007tortuga\032"
      " google/protobuf/descriptor.proto\",\n\021Tor"
      "tugaBridgeOpts\022\027\n\017timeout_seconds\030\001 \001(\005:"
      "L\n\006bridge\022\036.google.protobuf.MethodOption"
      "s\030\327\206\003 \001(\0132\032.tortuga.TortugaBridgeOptsB \n"
      "\nio.tortugaB\022TortugaParamsProto"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 231);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tortuga/tortuga_params.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2fdescriptor_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_tortuga_2ftortuga_5fparams_2eproto
namespace tortuga {

// ===================================================================

void TortugaBridgeOpts::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TortugaBridgeOpts::kTimeoutSecondsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TortugaBridgeOpts::TortugaBridgeOpts()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_tortuga_2ftortuga_5fparams_2eproto::InitDefaultsTortugaBridgeOpts();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tortuga.TortugaBridgeOpts)
}
TortugaBridgeOpts::TortugaBridgeOpts(const TortugaBridgeOpts& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  timeout_seconds_ = from.timeout_seconds_;
  // @@protoc_insertion_point(copy_constructor:tortuga.TortugaBridgeOpts)
}

void TortugaBridgeOpts::SharedCtor() {
  _cached_size_ = 0;
  timeout_seconds_ = 0;
}

TortugaBridgeOpts::~TortugaBridgeOpts() {
  // @@protoc_insertion_point(destructor:tortuga.TortugaBridgeOpts)
  SharedDtor();
}

void TortugaBridgeOpts::SharedDtor() {
}

void TortugaBridgeOpts::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TortugaBridgeOpts::descriptor() {
  ::protobuf_tortuga_2ftortuga_5fparams_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tortuga_2ftortuga_5fparams_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TortugaBridgeOpts& TortugaBridgeOpts::default_instance() {
  ::protobuf_tortuga_2ftortuga_5fparams_2eproto::InitDefaultsTortugaBridgeOpts();
  return *internal_default_instance();
}

TortugaBridgeOpts* TortugaBridgeOpts::New(::google::protobuf::Arena* arena) const {
  TortugaBridgeOpts* n = new TortugaBridgeOpts;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TortugaBridgeOpts::Clear() {
// @@protoc_insertion_point(message_clear_start:tortuga.TortugaBridgeOpts)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  timeout_seconds_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool TortugaBridgeOpts::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tortuga.TortugaBridgeOpts)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 timeout_seconds = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_timeout_seconds();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &timeout_seconds_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tortuga.TortugaBridgeOpts)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tortuga.TortugaBridgeOpts)
  return false;
#undef DO_
}

void TortugaBridgeOpts::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tortuga.TortugaBridgeOpts)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 timeout_seconds = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->timeout_seconds(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:tortuga.TortugaBridgeOpts)
}

::google::protobuf::uint8* TortugaBridgeOpts::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tortuga.TortugaBridgeOpts)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 timeout_seconds = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->timeout_seconds(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tortuga.TortugaBridgeOpts)
  return target;
}

size_t TortugaBridgeOpts::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tortuga.TortugaBridgeOpts)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // optional int32 timeout_seconds = 1;
  if (has_timeout_seconds()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->timeout_seconds());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TortugaBridgeOpts::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tortuga.TortugaBridgeOpts)
  GOOGLE_DCHECK_NE(&from, this);
  const TortugaBridgeOpts* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TortugaBridgeOpts>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tortuga.TortugaBridgeOpts)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tortuga.TortugaBridgeOpts)
    MergeFrom(*source);
  }
}

void TortugaBridgeOpts::MergeFrom(const TortugaBridgeOpts& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tortuga.TortugaBridgeOpts)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_timeout_seconds()) {
    set_timeout_seconds(from.timeout_seconds());
  }
}

void TortugaBridgeOpts::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tortuga.TortugaBridgeOpts)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TortugaBridgeOpts::CopyFrom(const TortugaBridgeOpts& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tortuga.TortugaBridgeOpts)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TortugaBridgeOpts::IsInitialized() const {
  return true;
}

void TortugaBridgeOpts::Swap(TortugaBridgeOpts* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TortugaBridgeOpts::InternalSwap(TortugaBridgeOpts* other) {
  using std::swap;
  swap(timeout_seconds_, other->timeout_seconds_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TortugaBridgeOpts::GetMetadata() const {
  protobuf_tortuga_2ftortuga_5fparams_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tortuga_2ftortuga_5fparams_2eproto::file_level_metadata[kIndexInFileMessages];
}

::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::tortuga::TortugaBridgeOpts >, 11, false >
  bridge(kBridgeFieldNumber, *::tortuga::TortugaBridgeOpts::internal_default_instance());

// @@protoc_insertion_point(namespace_scope)
}  // namespace tortuga

// @@protoc_insertion_point(global_scope)
